// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("impart");

/**
 * The Impart api endpoint
 */
export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint") ?? utilities.getEnv("IMPART_ENDPOINT");
    },
    enumerable: true,
});

/**
 * The Impart api token
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token") ?? utilities.getEnv("IMPART_TOKEN");
    },
    enumerable: true,
});

