// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface MonitorCondition {
    /**
     * Greater than, equal to, or less than (should be one of 'gt', 'lt', or 'eq')
     */
    comparator: string;
    /**
     * In milliseconds, the offset from now() for the time window.
     */
    delay: number;
    details: outputs.MonitorConditionDetails;
    /**
     * Number of occurrences that need to execute to have this condition be true.
     */
    threshold: number;
    /**
     * In milliseconds, the time span from now until when we should be counting events (for example, 60000 is all events in the last minute).
     */
    timePeriod: number;
}

export interface MonitorConditionDetails {
    /**
     * Strictly for event type monitors. A slug of the action the monitor is tracking.
     */
    action?: string;
    /**
     * Strictly for event type monitors. A slug of the actor type the monitor is tracking.
     */
    actorType?: string;
    /**
     * Strictly for event type monitors. A slug of the subject type the monitor is tracking.
     */
    subjectType?: string;
    /**
     * Strictly for metric type monitors. The tag the monitor is tracking.
     */
    tag?: string;
    /**
     * The type of monitor (should be one of 'event' or 'metric'
     */
    type: string;
}

export interface RuleScriptDependenciesDependency {
    /**
     * IDs of the rule script this rule depends on.
     */
    dependsOnRuleScriptIds: string[];
    /**
     * The ID of the rule script
     */
    ruleScriptId: string;
}

