// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package impart

import (
	"context"
	"reflect"

	"errors"
	"github.com/impart-security/pulumi-impart/sdk/go/impart/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
type RuleClientIdentifierStorage struct {
	pulumi.CustomResourceState

	// The capacity for the rule client identifier storage.
	Capacity pulumi.IntOutput `pulumi:"capacity"`
	// The description for the rule client identifier storage.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The name for the rule client identifier storage.
	Name pulumi.StringOutput `pulumi:"name"`
}

// NewRuleClientIdentifierStorage registers a new resource with the given unique name, arguments, and options.
func NewRuleClientIdentifierStorage(ctx *pulumi.Context,
	name string, args *RuleClientIdentifierStorageArgs, opts ...pulumi.ResourceOption) (*RuleClientIdentifierStorage, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Capacity == nil {
		return nil, errors.New("invalid value for required argument 'Capacity'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RuleClientIdentifierStorage
	err := ctx.RegisterResource("impart:index/ruleClientIdentifierStorage:RuleClientIdentifierStorage", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRuleClientIdentifierStorage gets an existing RuleClientIdentifierStorage resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRuleClientIdentifierStorage(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RuleClientIdentifierStorageState, opts ...pulumi.ResourceOption) (*RuleClientIdentifierStorage, error) {
	var resource RuleClientIdentifierStorage
	err := ctx.ReadResource("impart:index/ruleClientIdentifierStorage:RuleClientIdentifierStorage", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RuleClientIdentifierStorage resources.
type ruleClientIdentifierStorageState struct {
	// The capacity for the rule client identifier storage.
	Capacity *int `pulumi:"capacity"`
	// The description for the rule client identifier storage.
	Description *string `pulumi:"description"`
	// The name for the rule client identifier storage.
	Name *string `pulumi:"name"`
}

type RuleClientIdentifierStorageState struct {
	// The capacity for the rule client identifier storage.
	Capacity pulumi.IntPtrInput
	// The description for the rule client identifier storage.
	Description pulumi.StringPtrInput
	// The name for the rule client identifier storage.
	Name pulumi.StringPtrInput
}

func (RuleClientIdentifierStorageState) ElementType() reflect.Type {
	return reflect.TypeOf((*ruleClientIdentifierStorageState)(nil)).Elem()
}

type ruleClientIdentifierStorageArgs struct {
	// The capacity for the rule client identifier storage.
	Capacity int `pulumi:"capacity"`
	// The description for the rule client identifier storage.
	Description *string `pulumi:"description"`
	// The name for the rule client identifier storage.
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a RuleClientIdentifierStorage resource.
type RuleClientIdentifierStorageArgs struct {
	// The capacity for the rule client identifier storage.
	Capacity pulumi.IntInput
	// The description for the rule client identifier storage.
	Description pulumi.StringPtrInput
	// The name for the rule client identifier storage.
	Name pulumi.StringInput
}

func (RuleClientIdentifierStorageArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ruleClientIdentifierStorageArgs)(nil)).Elem()
}

type RuleClientIdentifierStorageInput interface {
	pulumi.Input

	ToRuleClientIdentifierStorageOutput() RuleClientIdentifierStorageOutput
	ToRuleClientIdentifierStorageOutputWithContext(ctx context.Context) RuleClientIdentifierStorageOutput
}

func (*RuleClientIdentifierStorage) ElementType() reflect.Type {
	return reflect.TypeOf((**RuleClientIdentifierStorage)(nil)).Elem()
}

func (i *RuleClientIdentifierStorage) ToRuleClientIdentifierStorageOutput() RuleClientIdentifierStorageOutput {
	return i.ToRuleClientIdentifierStorageOutputWithContext(context.Background())
}

func (i *RuleClientIdentifierStorage) ToRuleClientIdentifierStorageOutputWithContext(ctx context.Context) RuleClientIdentifierStorageOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuleClientIdentifierStorageOutput)
}

// RuleClientIdentifierStorageArrayInput is an input type that accepts RuleClientIdentifierStorageArray and RuleClientIdentifierStorageArrayOutput values.
// You can construct a concrete instance of `RuleClientIdentifierStorageArrayInput` via:
//
//	RuleClientIdentifierStorageArray{ RuleClientIdentifierStorageArgs{...} }
type RuleClientIdentifierStorageArrayInput interface {
	pulumi.Input

	ToRuleClientIdentifierStorageArrayOutput() RuleClientIdentifierStorageArrayOutput
	ToRuleClientIdentifierStorageArrayOutputWithContext(context.Context) RuleClientIdentifierStorageArrayOutput
}

type RuleClientIdentifierStorageArray []RuleClientIdentifierStorageInput

func (RuleClientIdentifierStorageArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RuleClientIdentifierStorage)(nil)).Elem()
}

func (i RuleClientIdentifierStorageArray) ToRuleClientIdentifierStorageArrayOutput() RuleClientIdentifierStorageArrayOutput {
	return i.ToRuleClientIdentifierStorageArrayOutputWithContext(context.Background())
}

func (i RuleClientIdentifierStorageArray) ToRuleClientIdentifierStorageArrayOutputWithContext(ctx context.Context) RuleClientIdentifierStorageArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuleClientIdentifierStorageArrayOutput)
}

// RuleClientIdentifierStorageMapInput is an input type that accepts RuleClientIdentifierStorageMap and RuleClientIdentifierStorageMapOutput values.
// You can construct a concrete instance of `RuleClientIdentifierStorageMapInput` via:
//
//	RuleClientIdentifierStorageMap{ "key": RuleClientIdentifierStorageArgs{...} }
type RuleClientIdentifierStorageMapInput interface {
	pulumi.Input

	ToRuleClientIdentifierStorageMapOutput() RuleClientIdentifierStorageMapOutput
	ToRuleClientIdentifierStorageMapOutputWithContext(context.Context) RuleClientIdentifierStorageMapOutput
}

type RuleClientIdentifierStorageMap map[string]RuleClientIdentifierStorageInput

func (RuleClientIdentifierStorageMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RuleClientIdentifierStorage)(nil)).Elem()
}

func (i RuleClientIdentifierStorageMap) ToRuleClientIdentifierStorageMapOutput() RuleClientIdentifierStorageMapOutput {
	return i.ToRuleClientIdentifierStorageMapOutputWithContext(context.Background())
}

func (i RuleClientIdentifierStorageMap) ToRuleClientIdentifierStorageMapOutputWithContext(ctx context.Context) RuleClientIdentifierStorageMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuleClientIdentifierStorageMapOutput)
}

type RuleClientIdentifierStorageOutput struct{ *pulumi.OutputState }

func (RuleClientIdentifierStorageOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RuleClientIdentifierStorage)(nil)).Elem()
}

func (o RuleClientIdentifierStorageOutput) ToRuleClientIdentifierStorageOutput() RuleClientIdentifierStorageOutput {
	return o
}

func (o RuleClientIdentifierStorageOutput) ToRuleClientIdentifierStorageOutputWithContext(ctx context.Context) RuleClientIdentifierStorageOutput {
	return o
}

// The capacity for the rule client identifier storage.
func (o RuleClientIdentifierStorageOutput) Capacity() pulumi.IntOutput {
	return o.ApplyT(func(v *RuleClientIdentifierStorage) pulumi.IntOutput { return v.Capacity }).(pulumi.IntOutput)
}

// The description for the rule client identifier storage.
func (o RuleClientIdentifierStorageOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RuleClientIdentifierStorage) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The name for the rule client identifier storage.
func (o RuleClientIdentifierStorageOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *RuleClientIdentifierStorage) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

type RuleClientIdentifierStorageArrayOutput struct{ *pulumi.OutputState }

func (RuleClientIdentifierStorageArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RuleClientIdentifierStorage)(nil)).Elem()
}

func (o RuleClientIdentifierStorageArrayOutput) ToRuleClientIdentifierStorageArrayOutput() RuleClientIdentifierStorageArrayOutput {
	return o
}

func (o RuleClientIdentifierStorageArrayOutput) ToRuleClientIdentifierStorageArrayOutputWithContext(ctx context.Context) RuleClientIdentifierStorageArrayOutput {
	return o
}

func (o RuleClientIdentifierStorageArrayOutput) Index(i pulumi.IntInput) RuleClientIdentifierStorageOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RuleClientIdentifierStorage {
		return vs[0].([]*RuleClientIdentifierStorage)[vs[1].(int)]
	}).(RuleClientIdentifierStorageOutput)
}

type RuleClientIdentifierStorageMapOutput struct{ *pulumi.OutputState }

func (RuleClientIdentifierStorageMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RuleClientIdentifierStorage)(nil)).Elem()
}

func (o RuleClientIdentifierStorageMapOutput) ToRuleClientIdentifierStorageMapOutput() RuleClientIdentifierStorageMapOutput {
	return o
}

func (o RuleClientIdentifierStorageMapOutput) ToRuleClientIdentifierStorageMapOutputWithContext(ctx context.Context) RuleClientIdentifierStorageMapOutput {
	return o
}

func (o RuleClientIdentifierStorageMapOutput) MapIndex(k pulumi.StringInput) RuleClientIdentifierStorageOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RuleClientIdentifierStorage {
		return vs[0].(map[string]*RuleClientIdentifierStorage)[vs[1].(string)]
	}).(RuleClientIdentifierStorageOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RuleClientIdentifierStorageInput)(nil)).Elem(), &RuleClientIdentifierStorage{})
	pulumi.RegisterInputType(reflect.TypeOf((*RuleClientIdentifierStorageArrayInput)(nil)).Elem(), RuleClientIdentifierStorageArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RuleClientIdentifierStorageMapInput)(nil)).Elem(), RuleClientIdentifierStorageMap{})
	pulumi.RegisterOutputType(RuleClientIdentifierStorageOutput{})
	pulumi.RegisterOutputType(RuleClientIdentifierStorageArrayOutput{})
	pulumi.RegisterOutputType(RuleClientIdentifierStorageMapOutput{})
}
