// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package impart

import (
	"context"
	"reflect"

	"errors"
	"github.com/impart-security/pulumi-impart/sdk/go/impart/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manage a rule script.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"fmt"
//	"os"
//
//	"github.com/impart-security/pulumi-impart/sdk/go/impart"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func readFileOrPanic(path string) pulumi.StringPtrInput {
//		data, err := os.ReadFile(path)
//		if err != nil {
//			panic(err.Error())
//		}
//		return pulumi.String(string(data))
//	}
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Create a new rule script
//			_, err := impart.NewRuleScript(ctx, "example", &impart.RuleScriptArgs{
//				Name:           pulumi.String("example"),
//				Disabled:       pulumi.Bool(false),
//				Description:    pulumi.String("Rule description"),
//				SourceFile:     pulumi.String(fmt.Sprintf("%v/rule.js", path.Module)),
//				SourceHash:     pulumi.String("<sha256 hash for the source_file content>"),
//				BlockingEffect: pulumi.String("block"),
//			})
//			if err != nil {
//				return err
//			}
//			// Create a new rule script with content
//			_, err = impart.NewRuleScript(ctx, "exampleContent", &impart.RuleScriptArgs{
//				Name:           pulumi.String("example"),
//				Disabled:       pulumi.Bool(false),
//				Description:    pulumi.String("Rule description"),
//				Content:        readFileOrPanic(fmt.Sprintf("%v/rule.js", path.Module)),
//				BlockingEffect: pulumi.String("block"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type RuleScript struct {
	pulumi.CustomResourceState

	// The rule blocking effect. Allowed values: block, simulate. If not set effect will be block.
	BlockingEffect pulumi.StringPtrOutput `pulumi:"blockingEffect"`
	// The rule body content.
	Content pulumi.StringPtrOutput `pulumi:"content"`
	// The description for this rule script.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Set true to disable the rule script.
	Disabled pulumi.BoolOutput `pulumi:"disabled"`
	// The name for this rule script.
	Name pulumi.StringOutput `pulumi:"name"`
	// The rule source file.
	SourceFile pulumi.StringPtrOutput `pulumi:"sourceFile"`
	// The rule source hash.
	SourceHash pulumi.StringPtrOutput `pulumi:"sourceHash"`
}

// NewRuleScript registers a new resource with the given unique name, arguments, and options.
func NewRuleScript(ctx *pulumi.Context,
	name string, args *RuleScriptArgs, opts ...pulumi.ResourceOption) (*RuleScript, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Disabled == nil {
		return nil, errors.New("invalid value for required argument 'Disabled'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RuleScript
	err := ctx.RegisterResource("impart:index/ruleScript:RuleScript", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRuleScript gets an existing RuleScript resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRuleScript(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RuleScriptState, opts ...pulumi.ResourceOption) (*RuleScript, error) {
	var resource RuleScript
	err := ctx.ReadResource("impart:index/ruleScript:RuleScript", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RuleScript resources.
type ruleScriptState struct {
	// The rule blocking effect. Allowed values: block, simulate. If not set effect will be block.
	BlockingEffect *string `pulumi:"blockingEffect"`
	// The rule body content.
	Content *string `pulumi:"content"`
	// The description for this rule script.
	Description *string `pulumi:"description"`
	// Set true to disable the rule script.
	Disabled *bool `pulumi:"disabled"`
	// The name for this rule script.
	Name *string `pulumi:"name"`
	// The rule source file.
	SourceFile *string `pulumi:"sourceFile"`
	// The rule source hash.
	SourceHash *string `pulumi:"sourceHash"`
}

type RuleScriptState struct {
	// The rule blocking effect. Allowed values: block, simulate. If not set effect will be block.
	BlockingEffect pulumi.StringPtrInput
	// The rule body content.
	Content pulumi.StringPtrInput
	// The description for this rule script.
	Description pulumi.StringPtrInput
	// Set true to disable the rule script.
	Disabled pulumi.BoolPtrInput
	// The name for this rule script.
	Name pulumi.StringPtrInput
	// The rule source file.
	SourceFile pulumi.StringPtrInput
	// The rule source hash.
	SourceHash pulumi.StringPtrInput
}

func (RuleScriptState) ElementType() reflect.Type {
	return reflect.TypeOf((*ruleScriptState)(nil)).Elem()
}

type ruleScriptArgs struct {
	// The rule blocking effect. Allowed values: block, simulate. If not set effect will be block.
	BlockingEffect *string `pulumi:"blockingEffect"`
	// The rule body content.
	Content *string `pulumi:"content"`
	// The description for this rule script.
	Description *string `pulumi:"description"`
	// Set true to disable the rule script.
	Disabled bool `pulumi:"disabled"`
	// The name for this rule script.
	Name string `pulumi:"name"`
	// The rule source file.
	SourceFile *string `pulumi:"sourceFile"`
	// The rule source hash.
	SourceHash *string `pulumi:"sourceHash"`
}

// The set of arguments for constructing a RuleScript resource.
type RuleScriptArgs struct {
	// The rule blocking effect. Allowed values: block, simulate. If not set effect will be block.
	BlockingEffect pulumi.StringPtrInput
	// The rule body content.
	Content pulumi.StringPtrInput
	// The description for this rule script.
	Description pulumi.StringPtrInput
	// Set true to disable the rule script.
	Disabled pulumi.BoolInput
	// The name for this rule script.
	Name pulumi.StringInput
	// The rule source file.
	SourceFile pulumi.StringPtrInput
	// The rule source hash.
	SourceHash pulumi.StringPtrInput
}

func (RuleScriptArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ruleScriptArgs)(nil)).Elem()
}

type RuleScriptInput interface {
	pulumi.Input

	ToRuleScriptOutput() RuleScriptOutput
	ToRuleScriptOutputWithContext(ctx context.Context) RuleScriptOutput
}

func (*RuleScript) ElementType() reflect.Type {
	return reflect.TypeOf((**RuleScript)(nil)).Elem()
}

func (i *RuleScript) ToRuleScriptOutput() RuleScriptOutput {
	return i.ToRuleScriptOutputWithContext(context.Background())
}

func (i *RuleScript) ToRuleScriptOutputWithContext(ctx context.Context) RuleScriptOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuleScriptOutput)
}

// RuleScriptArrayInput is an input type that accepts RuleScriptArray and RuleScriptArrayOutput values.
// You can construct a concrete instance of `RuleScriptArrayInput` via:
//
//	RuleScriptArray{ RuleScriptArgs{...} }
type RuleScriptArrayInput interface {
	pulumi.Input

	ToRuleScriptArrayOutput() RuleScriptArrayOutput
	ToRuleScriptArrayOutputWithContext(context.Context) RuleScriptArrayOutput
}

type RuleScriptArray []RuleScriptInput

func (RuleScriptArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RuleScript)(nil)).Elem()
}

func (i RuleScriptArray) ToRuleScriptArrayOutput() RuleScriptArrayOutput {
	return i.ToRuleScriptArrayOutputWithContext(context.Background())
}

func (i RuleScriptArray) ToRuleScriptArrayOutputWithContext(ctx context.Context) RuleScriptArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuleScriptArrayOutput)
}

// RuleScriptMapInput is an input type that accepts RuleScriptMap and RuleScriptMapOutput values.
// You can construct a concrete instance of `RuleScriptMapInput` via:
//
//	RuleScriptMap{ "key": RuleScriptArgs{...} }
type RuleScriptMapInput interface {
	pulumi.Input

	ToRuleScriptMapOutput() RuleScriptMapOutput
	ToRuleScriptMapOutputWithContext(context.Context) RuleScriptMapOutput
}

type RuleScriptMap map[string]RuleScriptInput

func (RuleScriptMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RuleScript)(nil)).Elem()
}

func (i RuleScriptMap) ToRuleScriptMapOutput() RuleScriptMapOutput {
	return i.ToRuleScriptMapOutputWithContext(context.Background())
}

func (i RuleScriptMap) ToRuleScriptMapOutputWithContext(ctx context.Context) RuleScriptMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RuleScriptMapOutput)
}

type RuleScriptOutput struct{ *pulumi.OutputState }

func (RuleScriptOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RuleScript)(nil)).Elem()
}

func (o RuleScriptOutput) ToRuleScriptOutput() RuleScriptOutput {
	return o
}

func (o RuleScriptOutput) ToRuleScriptOutputWithContext(ctx context.Context) RuleScriptOutput {
	return o
}

// The rule blocking effect. Allowed values: block, simulate. If not set effect will be block.
func (o RuleScriptOutput) BlockingEffect() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RuleScript) pulumi.StringPtrOutput { return v.BlockingEffect }).(pulumi.StringPtrOutput)
}

// The rule body content.
func (o RuleScriptOutput) Content() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RuleScript) pulumi.StringPtrOutput { return v.Content }).(pulumi.StringPtrOutput)
}

// The description for this rule script.
func (o RuleScriptOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RuleScript) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Set true to disable the rule script.
func (o RuleScriptOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *RuleScript) pulumi.BoolOutput { return v.Disabled }).(pulumi.BoolOutput)
}

// The name for this rule script.
func (o RuleScriptOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *RuleScript) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The rule source file.
func (o RuleScriptOutput) SourceFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RuleScript) pulumi.StringPtrOutput { return v.SourceFile }).(pulumi.StringPtrOutput)
}

// The rule source hash.
func (o RuleScriptOutput) SourceHash() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RuleScript) pulumi.StringPtrOutput { return v.SourceHash }).(pulumi.StringPtrOutput)
}

type RuleScriptArrayOutput struct{ *pulumi.OutputState }

func (RuleScriptArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RuleScript)(nil)).Elem()
}

func (o RuleScriptArrayOutput) ToRuleScriptArrayOutput() RuleScriptArrayOutput {
	return o
}

func (o RuleScriptArrayOutput) ToRuleScriptArrayOutputWithContext(ctx context.Context) RuleScriptArrayOutput {
	return o
}

func (o RuleScriptArrayOutput) Index(i pulumi.IntInput) RuleScriptOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RuleScript {
		return vs[0].([]*RuleScript)[vs[1].(int)]
	}).(RuleScriptOutput)
}

type RuleScriptMapOutput struct{ *pulumi.OutputState }

func (RuleScriptMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RuleScript)(nil)).Elem()
}

func (o RuleScriptMapOutput) ToRuleScriptMapOutput() RuleScriptMapOutput {
	return o
}

func (o RuleScriptMapOutput) ToRuleScriptMapOutputWithContext(ctx context.Context) RuleScriptMapOutput {
	return o
}

func (o RuleScriptMapOutput) MapIndex(k pulumi.StringInput) RuleScriptOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RuleScript {
		return vs[0].(map[string]*RuleScript)[vs[1].(string)]
	}).(RuleScriptOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RuleScriptInput)(nil)).Elem(), &RuleScript{})
	pulumi.RegisterInputType(reflect.TypeOf((*RuleScriptArrayInput)(nil)).Elem(), RuleScriptArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RuleScriptMapInput)(nil)).Elem(), RuleScriptMap{})
	pulumi.RegisterOutputType(RuleScriptOutput{})
	pulumi.RegisterOutputType(RuleScriptArrayOutput{})
	pulumi.RegisterOutputType(RuleScriptMapOutput{})
}
