// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage an api binding.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as impart from "@impart-security/pulumi-impart";
 *
 * // Create a new api binding
 * const example = new impart.ApiBinding("example", {
 *     name: "api_binding_example",
 *     port: 443,
 *     specId: impartSpec.example.id,
 *     hostname: "example.com",
 *     basePath: "/",
 * });
 * ```
 */
export class ApiBinding extends pulumi.CustomResource {
    /**
     * Get an existing ApiBinding resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApiBindingState, opts?: pulumi.CustomResourceOptions): ApiBinding {
        return new ApiBinding(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'impart:index/apiBinding:ApiBinding';

    /**
     * Returns true if the given object is an instance of ApiBinding.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApiBinding {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApiBinding.__pulumiType;
    }

    /**
     * The basePath for this api binding.
     */
    declare public readonly basePath: pulumi.Output<string>;
    /**
     * The disabled for this api binding.
     */
    declare public readonly disabled: pulumi.Output<boolean | undefined>;
    /**
     * The forwardedFor for this api binding.
     */
    declare public readonly forwardedFors: pulumi.Output<string[] | undefined>;
    /**
     * The forwardedHost for this api binding.
     */
    declare public readonly forwardedHosts: pulumi.Output<string[] | undefined>;
    /**
     * The forwardedId for this api binding.
     */
    declare public readonly forwardedIds: pulumi.Output<string[] | undefined>;
    /**
     * The forwardedProto for this api binding.
     */
    declare public readonly forwardedProtos: pulumi.Output<string[] | undefined>;
    /**
     * The hops for this api binding.
     */
    declare public readonly hops: pulumi.Output<number | undefined>;
    /**
     * The hostname for this api binding.
     */
    declare public readonly hostname: pulumi.Output<string>;
    /**
     * The name for this api binding.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The port for this api binding.
     */
    declare public readonly port: pulumi.Output<number>;
    /**
     * The specification id.
     */
    declare public readonly specId: pulumi.Output<string>;
    /**
     * The upstreamOrigin for this api binding.
     */
    declare public readonly upstreamOrigin: pulumi.Output<string | undefined>;
    /**
     * The useForwarded for this api binding.
     */
    declare public readonly useForwarded: pulumi.Output<boolean | undefined>;

    /**
     * Create a ApiBinding resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApiBindingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApiBindingArgs | ApiBindingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApiBindingState | undefined;
            resourceInputs["basePath"] = state?.basePath;
            resourceInputs["disabled"] = state?.disabled;
            resourceInputs["forwardedFors"] = state?.forwardedFors;
            resourceInputs["forwardedHosts"] = state?.forwardedHosts;
            resourceInputs["forwardedIds"] = state?.forwardedIds;
            resourceInputs["forwardedProtos"] = state?.forwardedProtos;
            resourceInputs["hops"] = state?.hops;
            resourceInputs["hostname"] = state?.hostname;
            resourceInputs["name"] = state?.name;
            resourceInputs["port"] = state?.port;
            resourceInputs["specId"] = state?.specId;
            resourceInputs["upstreamOrigin"] = state?.upstreamOrigin;
            resourceInputs["useForwarded"] = state?.useForwarded;
        } else {
            const args = argsOrState as ApiBindingArgs | undefined;
            if (args?.basePath === undefined && !opts.urn) {
                throw new Error("Missing required property 'basePath'");
            }
            if (args?.hostname === undefined && !opts.urn) {
                throw new Error("Missing required property 'hostname'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.port === undefined && !opts.urn) {
                throw new Error("Missing required property 'port'");
            }
            if (args?.specId === undefined && !opts.urn) {
                throw new Error("Missing required property 'specId'");
            }
            resourceInputs["basePath"] = args?.basePath;
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["forwardedFors"] = args?.forwardedFors;
            resourceInputs["forwardedHosts"] = args?.forwardedHosts;
            resourceInputs["forwardedIds"] = args?.forwardedIds;
            resourceInputs["forwardedProtos"] = args?.forwardedProtos;
            resourceInputs["hops"] = args?.hops;
            resourceInputs["hostname"] = args?.hostname;
            resourceInputs["name"] = args?.name;
            resourceInputs["port"] = args?.port;
            resourceInputs["specId"] = args?.specId;
            resourceInputs["upstreamOrigin"] = args?.upstreamOrigin;
            resourceInputs["useForwarded"] = args?.useForwarded;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ApiBinding.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ApiBinding resources.
 */
export interface ApiBindingState {
    /**
     * The basePath for this api binding.
     */
    basePath?: pulumi.Input<string>;
    /**
     * The disabled for this api binding.
     */
    disabled?: pulumi.Input<boolean>;
    /**
     * The forwardedFor for this api binding.
     */
    forwardedFors?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The forwardedHost for this api binding.
     */
    forwardedHosts?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The forwardedId for this api binding.
     */
    forwardedIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The forwardedProto for this api binding.
     */
    forwardedProtos?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The hops for this api binding.
     */
    hops?: pulumi.Input<number>;
    /**
     * The hostname for this api binding.
     */
    hostname?: pulumi.Input<string>;
    /**
     * The name for this api binding.
     */
    name?: pulumi.Input<string>;
    /**
     * The port for this api binding.
     */
    port?: pulumi.Input<number>;
    /**
     * The specification id.
     */
    specId?: pulumi.Input<string>;
    /**
     * The upstreamOrigin for this api binding.
     */
    upstreamOrigin?: pulumi.Input<string>;
    /**
     * The useForwarded for this api binding.
     */
    useForwarded?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a ApiBinding resource.
 */
export interface ApiBindingArgs {
    /**
     * The basePath for this api binding.
     */
    basePath: pulumi.Input<string>;
    /**
     * The disabled for this api binding.
     */
    disabled?: pulumi.Input<boolean>;
    /**
     * The forwardedFor for this api binding.
     */
    forwardedFors?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The forwardedHost for this api binding.
     */
    forwardedHosts?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The forwardedId for this api binding.
     */
    forwardedIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The forwardedProto for this api binding.
     */
    forwardedProtos?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The hops for this api binding.
     */
    hops?: pulumi.Input<number>;
    /**
     * The hostname for this api binding.
     */
    hostname: pulumi.Input<string>;
    /**
     * The name for this api binding.
     */
    name: pulumi.Input<string>;
    /**
     * The port for this api binding.
     */
    port: pulumi.Input<number>;
    /**
     * The specification id.
     */
    specId: pulumi.Input<string>;
    /**
     * The upstreamOrigin for this api binding.
     */
    upstreamOrigin?: pulumi.Input<string>;
    /**
     * The useForwarded for this api binding.
     */
    useForwarded?: pulumi.Input<boolean>;
}
