// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a core rule configuration.
 */
export class CoreRuleConfig extends pulumi.CustomResource {
    /**
     * Get an existing CoreRuleConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CoreRuleConfigState, opts?: pulumi.CustomResourceOptions): CoreRuleConfig {
        return new CoreRuleConfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'impart:index/coreRuleConfig:CoreRuleConfig';

    /**
     * Returns true if the given object is an instance of CoreRuleConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CoreRuleConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CoreRuleConfig.__pulumiType;
    }

    /**
     * the core rule configuration.
     */
    public readonly config!: pulumi.Output<string>;
    /**
     * Set true to disable the core rule.
     */
    public readonly disabled!: pulumi.Output<boolean>;
    /**
     * The slug for the core rule.
     */
    public readonly slug!: pulumi.Output<string>;

    /**
     * Create a CoreRuleConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CoreRuleConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CoreRuleConfigArgs | CoreRuleConfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CoreRuleConfigState | undefined;
            resourceInputs["config"] = state ? state.config : undefined;
            resourceInputs["disabled"] = state ? state.disabled : undefined;
            resourceInputs["slug"] = state ? state.slug : undefined;
        } else {
            const args = argsOrState as CoreRuleConfigArgs | undefined;
            if ((!args || args.config === undefined) && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if ((!args || args.disabled === undefined) && !opts.urn) {
                throw new Error("Missing required property 'disabled'");
            }
            if ((!args || args.slug === undefined) && !opts.urn) {
                throw new Error("Missing required property 'slug'");
            }
            resourceInputs["config"] = args ? args.config : undefined;
            resourceInputs["disabled"] = args ? args.disabled : undefined;
            resourceInputs["slug"] = args ? args.slug : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CoreRuleConfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CoreRuleConfig resources.
 */
export interface CoreRuleConfigState {
    /**
     * the core rule configuration.
     */
    config?: pulumi.Input<string>;
    /**
     * Set true to disable the core rule.
     */
    disabled?: pulumi.Input<boolean>;
    /**
     * The slug for the core rule.
     */
    slug?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CoreRuleConfig resource.
 */
export interface CoreRuleConfigArgs {
    /**
     * the core rule configuration.
     */
    config: pulumi.Input<string>;
    /**
     * Set true to disable the core rule.
     */
    disabled: pulumi.Input<boolean>;
    /**
     * The slug for the core rule.
     */
    slug: pulumi.Input<string>;
}
