// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a specification.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as impart from "@impart-security/pulumi-impart";
 *
 * // Read in an existing specification
 * const example = impart.GetSpec({
 *     id: "<id>",
 * });
 * ```
 */
export function getSpec(args: GetSpecArgs, opts?: pulumi.InvokeOptions): Promise<GetSpecResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("impart:index/getSpec:GetSpec", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking GetSpec.
 */
export interface GetSpecArgs {
    /**
     * Identifier for this specification.
     */
    id: string;
}

/**
 * A collection of values returned by GetSpec.
 */
export interface GetSpecResult {
    /**
     * Identifier for this specification.
     */
    readonly id: string;
    /**
     * The name for this specification.
     */
    readonly name: string;
}
/**
 * Manage a specification.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as impart from "@impart-security/pulumi-impart";
 *
 * // Read in an existing specification
 * const example = impart.GetSpec({
 *     id: "<id>",
 * });
 * ```
 */
export function getSpecOutput(args: GetSpecOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSpecResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("impart:index/getSpec:GetSpec", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking GetSpec.
 */
export interface GetSpecOutputArgs {
    /**
     * Identifier for this specification.
     */
    id: pulumi.Input<string>;
}
