// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ApiBindingArgs, ApiBindingState } from "./apiBinding";
export type ApiBinding = import("./apiBinding").ApiBinding;
export const ApiBinding: typeof import("./apiBinding").ApiBinding = null as any;
utilities.lazyLoad(exports, ["ApiBinding"], () => require("./apiBinding"));

export { ExternalLinkArgs, ExternalLinkState } from "./externalLink";
export type ExternalLink = import("./externalLink").ExternalLink;
export const ExternalLink: typeof import("./externalLink").ExternalLink = null as any;
utilities.lazyLoad(exports, ["ExternalLink"], () => require("./externalLink"));

export { GetConnectorArgs, GetConnectorResult, GetConnectorOutputArgs } from "./getConnector";
export const getConnector: typeof import("./getConnector").getConnector = null as any;
export const getConnectorOutput: typeof import("./getConnector").getConnectorOutput = null as any;
utilities.lazyLoad(exports, ["getConnector","getConnectorOutput"], () => require("./getConnector"));

export { GetSpecArgs, GetSpecResult, GetSpecOutputArgs } from "./getSpec";
export const getSpec: typeof import("./getSpec").getSpec = null as any;
export const getSpecOutput: typeof import("./getSpec").getSpecOutput = null as any;
utilities.lazyLoad(exports, ["getSpec","getSpecOutput"], () => require("./getSpec"));

export { LabelArgs, LabelState } from "./label";
export type Label = import("./label").Label;
export const Label: typeof import("./label").Label = null as any;
utilities.lazyLoad(exports, ["Label"], () => require("./label"));

export { ListArgs, ListState } from "./list";
export type List = import("./list").List;
export const List: typeof import("./list").List = null as any;
utilities.lazyLoad(exports, ["List"], () => require("./list"));

export { LogBindingArgs, LogBindingState } from "./logBinding";
export type LogBinding = import("./logBinding").LogBinding;
export const LogBinding: typeof import("./logBinding").LogBinding = null as any;
utilities.lazyLoad(exports, ["LogBinding"], () => require("./logBinding"));

export { MonitorArgs, MonitorState } from "./monitor";
export type Monitor = import("./monitor").Monitor;
export const Monitor: typeof import("./monitor").Monitor = null as any;
utilities.lazyLoad(exports, ["Monitor"], () => require("./monitor"));

export { NotificationTemplateArgs, NotificationTemplateState } from "./notificationTemplate";
export type NotificationTemplate = import("./notificationTemplate").NotificationTemplate;
export const NotificationTemplate: typeof import("./notificationTemplate").NotificationTemplate = null as any;
utilities.lazyLoad(exports, ["NotificationTemplate"], () => require("./notificationTemplate"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { RuleScriptArgs, RuleScriptState } from "./ruleScript";
export type RuleScript = import("./ruleScript").RuleScript;
export const RuleScript: typeof import("./ruleScript").RuleScript = null as any;
utilities.lazyLoad(exports, ["RuleScript"], () => require("./ruleScript"));

export { RuleScriptDependenciesArgs, RuleScriptDependenciesState } from "./ruleScriptDependencies";
export type RuleScriptDependencies = import("./ruleScriptDependencies").RuleScriptDependencies;
export const RuleScriptDependencies: typeof import("./ruleScriptDependencies").RuleScriptDependencies = null as any;
utilities.lazyLoad(exports, ["RuleScriptDependencies"], () => require("./ruleScriptDependencies"));

export { RuleTestCaseArgs, RuleTestCaseState } from "./ruleTestCase";
export type RuleTestCase = import("./ruleTestCase").RuleTestCase;
export const RuleTestCase: typeof import("./ruleTestCase").RuleTestCase = null as any;
utilities.lazyLoad(exports, ["RuleTestCase"], () => require("./ruleTestCase"));

export { SpecArgs, SpecState } from "./spec";
export type Spec = import("./spec").Spec;
export const Spec: typeof import("./spec").Spec = null as any;
utilities.lazyLoad(exports, ["Spec"], () => require("./spec"));

export { TagMetadataArgs, TagMetadataState } from "./tagMetadata";
export type TagMetadata = import("./tagMetadata").TagMetadata;
export const TagMetadata: typeof import("./tagMetadata").TagMetadata = null as any;
utilities.lazyLoad(exports, ["TagMetadata"], () => require("./tagMetadata"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "impart:index/apiBinding:ApiBinding":
                return new ApiBinding(name, <any>undefined, { urn })
            case "impart:index/externalLink:ExternalLink":
                return new ExternalLink(name, <any>undefined, { urn })
            case "impart:index/label:Label":
                return new Label(name, <any>undefined, { urn })
            case "impart:index/list:List":
                return new List(name, <any>undefined, { urn })
            case "impart:index/logBinding:LogBinding":
                return new LogBinding(name, <any>undefined, { urn })
            case "impart:index/monitor:Monitor":
                return new Monitor(name, <any>undefined, { urn })
            case "impart:index/notificationTemplate:NotificationTemplate":
                return new NotificationTemplate(name, <any>undefined, { urn })
            case "impart:index/ruleScript:RuleScript":
                return new RuleScript(name, <any>undefined, { urn })
            case "impart:index/ruleScriptDependencies:RuleScriptDependencies":
                return new RuleScriptDependencies(name, <any>undefined, { urn })
            case "impart:index/ruleTestCase:RuleTestCase":
                return new RuleTestCase(name, <any>undefined, { urn })
            case "impart:index/spec:Spec":
                return new Spec(name, <any>undefined, { urn })
            case "impart:index/tagMetadata:TagMetadata":
                return new TagMetadata(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("impart", "index/apiBinding", _module)
pulumi.runtime.registerResourceModule("impart", "index/externalLink", _module)
pulumi.runtime.registerResourceModule("impart", "index/label", _module)
pulumi.runtime.registerResourceModule("impart", "index/list", _module)
pulumi.runtime.registerResourceModule("impart", "index/logBinding", _module)
pulumi.runtime.registerResourceModule("impart", "index/monitor", _module)
pulumi.runtime.registerResourceModule("impart", "index/notificationTemplate", _module)
pulumi.runtime.registerResourceModule("impart", "index/ruleScript", _module)
pulumi.runtime.registerResourceModule("impart", "index/ruleScriptDependencies", _module)
pulumi.runtime.registerResourceModule("impart", "index/ruleTestCase", _module)
pulumi.runtime.registerResourceModule("impart", "index/spec", _module)
pulumi.runtime.registerResourceModule("impart", "index/tagMetadata", _module)
pulumi.runtime.registerResourcePackage("impart", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:impart") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
