// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manage a list.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as impart from "@impart-security/pulumi-impart";
 *
 * // Create a new string list
 * const example = new impart.List("example", {
 *     name: "list_example",
 *     kind: "string",
 *     description: "list description",
 *     items: [
 *         {
 *             value: "item1",
 *         },
 *         {
 *             value: "item2",
 *         },
 *     ],
 * });
 * // Create a regex pattern list
 * const regexExample = new impart.List("regex_example", {
 *     name: "regex_list_example",
 *     kind: "regex",
 *     description: "A list of regex patterns for matching",
 *     items: [
 *         {
 *             value: "^/api/v[0-9]+/users/.*$",
 *         },
 *         {
 *             value: "\\.(php|asp|aspx)$",
 *         },
 *     ],
 * });
 * // Create an Aho-Corasick pattern list
 * const ahoCorasickExample = new impart.List("aho_corasick_example", {
 *     name: "aho_corasick_list_example",
 *     kind: "aho_corasick",
 *     description: "A list of patterns for Aho-Corasick matching",
 *     items: [
 *         {
 *             value: "SELECT * FROM",
 *         },
 *         {
 *             value: "DROP TABLE",
 *         },
 *     ],
 * });
 * ```
 */
export class List extends pulumi.CustomResource {
    /**
     * Get an existing List resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ListState, opts?: pulumi.CustomResourceOptions): List {
        return new List(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'impart:index/list:List';

    /**
     * Returns true if the given object is an instance of List.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is List {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === List.__pulumiType;
    }

    /**
     * The description for this list.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The list functionality. Allowed values are add, add/remove, and none (cloud managed).
     */
    declare public readonly functionality: pulumi.Output<string | undefined>;
    /**
     * The list items.
     */
    declare public readonly items: pulumi.Output<outputs.ListItem[] | undefined>;
    /**
     * The list kind.
     */
    declare public readonly kind: pulumi.Output<string>;
    /**
     * The applied labels.
     */
    declare public readonly labels: pulumi.Output<string[] | undefined>;
    /**
     * The name for this list.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The list subkind.
     */
    declare public readonly subkind: pulumi.Output<string | undefined>;

    /**
     * Create a List resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ListArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ListArgs | ListState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ListState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["functionality"] = state?.functionality;
            resourceInputs["items"] = state?.items;
            resourceInputs["kind"] = state?.kind;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["name"] = state?.name;
            resourceInputs["subkind"] = state?.subkind;
        } else {
            const args = argsOrState as ListArgs | undefined;
            if (args?.kind === undefined && !opts.urn) {
                throw new Error("Missing required property 'kind'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["functionality"] = args?.functionality;
            resourceInputs["items"] = args?.items;
            resourceInputs["kind"] = args?.kind;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["name"] = args?.name;
            resourceInputs["subkind"] = args?.subkind;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(List.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering List resources.
 */
export interface ListState {
    /**
     * The description for this list.
     */
    description?: pulumi.Input<string>;
    /**
     * The list functionality. Allowed values are add, add/remove, and none (cloud managed).
     */
    functionality?: pulumi.Input<string>;
    /**
     * The list items.
     */
    items?: pulumi.Input<pulumi.Input<inputs.ListItem>[]>;
    /**
     * The list kind.
     */
    kind?: pulumi.Input<string>;
    /**
     * The applied labels.
     */
    labels?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name for this list.
     */
    name?: pulumi.Input<string>;
    /**
     * The list subkind.
     */
    subkind?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a List resource.
 */
export interface ListArgs {
    /**
     * The description for this list.
     */
    description?: pulumi.Input<string>;
    /**
     * The list functionality. Allowed values are add, add/remove, and none (cloud managed).
     */
    functionality?: pulumi.Input<string>;
    /**
     * The list items.
     */
    items?: pulumi.Input<pulumi.Input<inputs.ListItem>[]>;
    /**
     * The list kind.
     */
    kind: pulumi.Input<string>;
    /**
     * The applied labels.
     */
    labels?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name for this list.
     */
    name: pulumi.Input<string>;
    /**
     * The list subkind.
     */
    subkind?: pulumi.Input<string>;
}
