// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as impart from "@impart-security/pulumi-impart";
 * import * as std from "@pulumi/std";
 *
 * const example = new impart.RuleTestCase("example", {
 *     name: "example",
 *     description: "test case description",
 *     messages: [{
 *         count: 1,
 *         req: {
 *             url: "http://example.com",
 *             method: "GET",
 *             body: std.base64encode({
 *                 input: "request body",
 *             }).then(invoke => invoke.result),
 *             headerKeys: ["Header1"],
 *             headerValues: ["value1"],
 *             remoteAddr: "192.168.1.1",
 *         },
 *         res: {
 *             statusCode: 201,
 *             headerKeys: ["Header1"],
 *             headerValues: ["value1"],
 *             body: std.base64encode({
 *                 input: "response body",
 *             }).then(invoke => invoke.result),
 *         },
 *     }],
 *     assertions: [
 *         {
 *             messageIndexes: [0],
 *             assertionType: "output",
 *             condition: "contains",
 *             expected: "test",
 *         },
 *         {
 *             messageIndexes: [0],
 *             assertionType: "block",
 *             location: "req",
 *             expected: "true",
 *         },
 *         {
 *             messageIndexes: [0],
 *             assertionType: "status_code",
 *             location: "req",
 *             condition: "one_of",
 *             expected: "201,200",
 *         },
 *         {
 *             messageIndexes: [0],
 *             assertionType: "tags",
 *             location: "req",
 *             condition: "contains",
 *             expected: "tagname",
 *         },
 *     ],
 * });
 * ```
 */
export class RuleTestCase extends pulumi.CustomResource {
    /**
     * Get an existing RuleTestCase resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RuleTestCaseState, opts?: pulumi.CustomResourceOptions): RuleTestCase {
        return new RuleTestCase(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'impart:index/ruleTestCase:RuleTestCase';

    /**
     * Returns true if the given object is an instance of RuleTestCase.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RuleTestCase {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RuleTestCase.__pulumiType;
    }

    /**
     * The assertions of the test case.
     */
    declare public readonly assertions: pulumi.Output<outputs.RuleTestCaseAssertion[] | undefined>;
    /**
     * The description of the test case.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The applied labels.
     */
    declare public readonly labels: pulumi.Output<string[] | undefined>;
    /**
     * The messages of the test case.
     */
    declare public readonly messages: pulumi.Output<outputs.RuleTestCaseMessage[]>;
    /**
     * The name of the test case.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Sets if test case required to pass on update.
     */
    declare public readonly required: pulumi.Output<boolean | undefined>;

    /**
     * Create a RuleTestCase resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RuleTestCaseArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RuleTestCaseArgs | RuleTestCaseState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RuleTestCaseState | undefined;
            resourceInputs["assertions"] = state?.assertions;
            resourceInputs["description"] = state?.description;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["messages"] = state?.messages;
            resourceInputs["name"] = state?.name;
            resourceInputs["required"] = state?.required;
        } else {
            const args = argsOrState as RuleTestCaseArgs | undefined;
            if (args?.messages === undefined && !opts.urn) {
                throw new Error("Missing required property 'messages'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["assertions"] = args?.assertions;
            resourceInputs["description"] = args?.description;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["messages"] = args?.messages;
            resourceInputs["name"] = args?.name;
            resourceInputs["required"] = args?.required;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RuleTestCase.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RuleTestCase resources.
 */
export interface RuleTestCaseState {
    /**
     * The assertions of the test case.
     */
    assertions?: pulumi.Input<pulumi.Input<inputs.RuleTestCaseAssertion>[]>;
    /**
     * The description of the test case.
     */
    description?: pulumi.Input<string>;
    /**
     * The applied labels.
     */
    labels?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The messages of the test case.
     */
    messages?: pulumi.Input<pulumi.Input<inputs.RuleTestCaseMessage>[]>;
    /**
     * The name of the test case.
     */
    name?: pulumi.Input<string>;
    /**
     * Sets if test case required to pass on update.
     */
    required?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a RuleTestCase resource.
 */
export interface RuleTestCaseArgs {
    /**
     * The assertions of the test case.
     */
    assertions?: pulumi.Input<pulumi.Input<inputs.RuleTestCaseAssertion>[]>;
    /**
     * The description of the test case.
     */
    description?: pulumi.Input<string>;
    /**
     * The applied labels.
     */
    labels?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The messages of the test case.
     */
    messages: pulumi.Input<pulumi.Input<inputs.RuleTestCaseMessage>[]>;
    /**
     * The name of the test case.
     */
    name: pulumi.Input<string>;
    /**
     * Sets if test case required to pass on update.
     */
    required?: pulumi.Input<boolean>;
}
