// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a rule.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as fs from "fs";
 * import * as impart from "@impart-security/pulumi-impart";
 *
 * // Create a new rule script
 * const example = new impart.Rule("example", {
 *     name: "example",
 *     disabled: false,
 *     description: "Rule description",
 *     sourceFile: `${path.module}/rule.js`,
 *     sourceHash: "<sha256 hash for the source_file content>",
 *     blockingEffect: "block",
 *     type: "script",
 * });
 * // Create a new rule recipe with content
 * const exampleRuleRecipe = new impart.Rule("exampleRuleRecipe", {
 *     name: "example",
 *     disabled: false,
 *     description: "Rule description",
 *     content: fs.readFileSync(`${path.module}/rule.json`, "utf8"),
 *     blockingEffect: "block",
 *     type: "recipe",
 * });
 * ```
 */
export class Rule extends pulumi.CustomResource {
    /**
     * Get an existing Rule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RuleState, opts?: pulumi.CustomResourceOptions): Rule {
        return new Rule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'impart:index/rule:Rule';

    /**
     * Returns true if the given object is an instance of Rule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Rule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Rule.__pulumiType;
    }

    /**
     * The rule blocking effect. Allowed values: block, simulate. If not set effect will be block.
     */
    public readonly blockingEffect!: pulumi.Output<string | undefined>;
    /**
     * The rule body content.
     */
    public readonly content!: pulumi.Output<string | undefined>;
    /**
     * The description for this rule.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Set true to disable the rule.
     */
    public readonly disabled!: pulumi.Output<boolean>;
    /**
     * The applied labels.
     */
    public readonly labels!: pulumi.Output<string[] | undefined>;
    /**
     * The name for this rule.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The rule source file.
     */
    public readonly sourceFile!: pulumi.Output<string | undefined>;
    /**
     * The rule source hash.
     */
    public readonly sourceHash!: pulumi.Output<string | undefined>;
    /**
     * The type of the rule. Allowed values: script, recipe.
     */
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a Rule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RuleArgs | RuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RuleState | undefined;
            resourceInputs["blockingEffect"] = state ? state.blockingEffect : undefined;
            resourceInputs["content"] = state ? state.content : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["disabled"] = state ? state.disabled : undefined;
            resourceInputs["labels"] = state ? state.labels : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["sourceFile"] = state ? state.sourceFile : undefined;
            resourceInputs["sourceHash"] = state ? state.sourceHash : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as RuleArgs | undefined;
            if ((!args || args.disabled === undefined) && !opts.urn) {
                throw new Error("Missing required property 'disabled'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["blockingEffect"] = args ? args.blockingEffect : undefined;
            resourceInputs["content"] = args ? args.content : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["disabled"] = args ? args.disabled : undefined;
            resourceInputs["labels"] = args ? args.labels : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["sourceFile"] = args ? args.sourceFile : undefined;
            resourceInputs["sourceHash"] = args ? args.sourceHash : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Rule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Rule resources.
 */
export interface RuleState {
    /**
     * The rule blocking effect. Allowed values: block, simulate. If not set effect will be block.
     */
    blockingEffect?: pulumi.Input<string>;
    /**
     * The rule body content.
     */
    content?: pulumi.Input<string>;
    /**
     * The description for this rule.
     */
    description?: pulumi.Input<string>;
    /**
     * Set true to disable the rule.
     */
    disabled?: pulumi.Input<boolean>;
    /**
     * The applied labels.
     */
    labels?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name for this rule.
     */
    name?: pulumi.Input<string>;
    /**
     * The rule source file.
     */
    sourceFile?: pulumi.Input<string>;
    /**
     * The rule source hash.
     */
    sourceHash?: pulumi.Input<string>;
    /**
     * The type of the rule. Allowed values: script, recipe.
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Rule resource.
 */
export interface RuleArgs {
    /**
     * The rule blocking effect. Allowed values: block, simulate. If not set effect will be block.
     */
    blockingEffect?: pulumi.Input<string>;
    /**
     * The rule body content.
     */
    content?: pulumi.Input<string>;
    /**
     * The description for this rule.
     */
    description?: pulumi.Input<string>;
    /**
     * Set true to disable the rule.
     */
    disabled: pulumi.Input<boolean>;
    /**
     * The applied labels.
     */
    labels?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name for this rule.
     */
    name: pulumi.Input<string>;
    /**
     * The rule source file.
     */
    sourceFile?: pulumi.Input<string>;
    /**
     * The rule source hash.
     */
    sourceHash?: pulumi.Input<string>;
    /**
     * The type of the rule. Allowed values: script, recipe.
     */
    type: pulumi.Input<string>;
}
