// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manage rule dependencies. There should only ever be one instance of this resource in a workspace at once, because it manages rule dependencies at an organization level.
 */
export class RuleDependencies extends pulumi.CustomResource {
    /**
     * Get an existing RuleDependencies resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RuleDependenciesState, opts?: pulumi.CustomResourceOptions): RuleDependencies {
        return new RuleDependencies(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'impart:index/ruleDependencies:RuleDependencies';

    /**
     * Returns true if the given object is an instance of RuleDependencies.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RuleDependencies {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RuleDependencies.__pulumiType;
    }

    /**
     * An array of rules and the other ids of the rules they depend on before executing.
     */
    public readonly dependencies!: pulumi.Output<outputs.RuleDependenciesDependency[]>;

    /**
     * Create a RuleDependencies resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RuleDependenciesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RuleDependenciesArgs | RuleDependenciesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RuleDependenciesState | undefined;
            resourceInputs["dependencies"] = state ? state.dependencies : undefined;
        } else {
            const args = argsOrState as RuleDependenciesArgs | undefined;
            if ((!args || args.dependencies === undefined) && !opts.urn) {
                throw new Error("Missing required property 'dependencies'");
            }
            resourceInputs["dependencies"] = args ? args.dependencies : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RuleDependencies.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RuleDependencies resources.
 */
export interface RuleDependenciesState {
    /**
     * An array of rules and the other ids of the rules they depend on before executing.
     */
    dependencies?: pulumi.Input<pulumi.Input<inputs.RuleDependenciesDependency>[]>;
}

/**
 * The set of arguments for constructing a RuleDependencies resource.
 */
export interface RuleDependenciesArgs {
    /**
     * An array of rules and the other ids of the rules they depend on before executing.
     */
    dependencies: pulumi.Input<pulumi.Input<inputs.RuleDependenciesDependency>[]>;
}
