// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 */
export class RuleClientIdentifierStorage extends pulumi.CustomResource {
    /**
     * Get an existing RuleClientIdentifierStorage resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RuleClientIdentifierStorageState, opts?: pulumi.CustomResourceOptions): RuleClientIdentifierStorage {
        return new RuleClientIdentifierStorage(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'impart:index/ruleClientIdentifierStorage:RuleClientIdentifierStorage';

    /**
     * Returns true if the given object is an instance of RuleClientIdentifierStorage.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RuleClientIdentifierStorage {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RuleClientIdentifierStorage.__pulumiType;
    }

    /**
     * The capacity for the rule client identifier storage.
     */
    public readonly capacity!: pulumi.Output<number>;
    /**
     * The description for the rule client identifier storage.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The name for the rule client identifier storage.
     */
    public readonly name!: pulumi.Output<string>;

    /**
     * Create a RuleClientIdentifierStorage resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RuleClientIdentifierStorageArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RuleClientIdentifierStorageArgs | RuleClientIdentifierStorageState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RuleClientIdentifierStorageState | undefined;
            resourceInputs["capacity"] = state ? state.capacity : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as RuleClientIdentifierStorageArgs | undefined;
            if ((!args || args.capacity === undefined) && !opts.urn) {
                throw new Error("Missing required property 'capacity'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["capacity"] = args ? args.capacity : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RuleClientIdentifierStorage.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RuleClientIdentifierStorage resources.
 */
export interface RuleClientIdentifierStorageState {
    /**
     * The capacity for the rule client identifier storage.
     */
    capacity?: pulumi.Input<number>;
    /**
     * The description for the rule client identifier storage.
     */
    description?: pulumi.Input<string>;
    /**
     * The name for the rule client identifier storage.
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RuleClientIdentifierStorage resource.
 */
export interface RuleClientIdentifierStorageArgs {
    /**
     * The capacity for the rule client identifier storage.
     */
    capacity: pulumi.Input<number>;
    /**
     * The description for the rule client identifier storage.
     */
    description?: pulumi.Input<string>;
    /**
     * The name for the rule client identifier storage.
     */
    name: pulumi.Input<string>;
}
